'use client';

import { AnalyzeResponse } from '@/types/kit';

interface DownloadButtonProps {
  data: AnalyzeResponse;
}

export default function DownloadButton({ data }: DownloadButtonProps) {
  const generateMarkdown = (): string => {
    const { owner, repo, kit } = data;
    const date = new Date().toISOString().split('T')[0];

    let md = `# DevLift Onboarding Kit: ${owner}/${repo}\n`;
    md += `Generated by DevLift powered by IBM watsonx.ai\n`;
    md += `Date: ${date}\n\n`;

    // Architecture Overview
    md += `## Architecture Overview\n\n`;
    md += `${kit.architecture_overview}\n\n`;

    // Key Components
    md += `## Key Components\n\n`;
    kit.key_components.forEach((component) => {
      md += `### ${component.name}\n`;
      md += `**Path:** \`${component.path}\`\n\n`;
      md += `${component.description}\n\n`;
    });

    // Complexity Hotspots
    md += `## Complexity Hotspots\n\n`;
    kit.complexity_hotspots.forEach((hotspot) => {
      md += `### ${hotspot.name}\n`;
      md += `**Path:** \`${hotspot.path}\`\n\n`;
      md += `**Why:** ${hotspot.reason}\n\n`;
      md += `**Tip:** ${hotspot.tip}\n\n`;
    });

    // Suggested First Tasks
    md += `## Suggested First Tasks\n\n`;
    kit.suggested_first_tasks.forEach((task) => {
      md += `### [${task.difficulty}] ${task.title}\n\n`;
      md += `${task.description}\n\n`;
    });

    // Common Patterns
    md += `## Common Patterns\n\n`;
    kit.common_patterns.forEach((pattern) => {
      md += `### ${pattern.pattern}\n\n`;
      md += `${pattern.description}\n\n`;
      md += `**Example:**\n\`\`\`\n${pattern.example}\n\`\`\`\n\n`;
    });

    // Setup & Run
    md += `## Setup & Run\n\n`;
    md += `### Prerequisites\n\n`;
    kit.setup_summary.prerequisites.forEach((prereq) => {
      md += `- ${prereq}\n`;
    });
    md += `\n### Installation\n\n`;
    kit.setup_summary.install_steps.forEach((step, idx) => {
      md += `${idx + 1}. ${step}\n`;
    });
    md += `\n### Run\n\n`;
    md += `\`\`\`\n${kit.setup_summary.run_command}\n\`\`\`\n\n`;
    md += `### Tests\n\n`;
    md += `\`\`\`\n${kit.setup_summary.test_command}\n\`\`\`\n\n`;
    md += `### Notes\n\n`;
    md += `${kit.setup_summary.notes}\n`;

    return md;
  };

  const handleDownload = () => {
    const markdown = generateMarkdown();
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `devlift-${data.repo}-kit.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleDownload}
      className="w-full mt-6 py-3.5 rounded-xl text-sm font-medium transition-all duration-200 bg-transparent border border-border text-muted-foreground hover:text-ibm-blue"
      style={{
        '--hover-border': 'rgba(0, 98, 255, 0.3)',
        '--hover-bg': 'rgba(0, 98, 255, 0.08)'
      } as React.CSSProperties}
      onMouseEnter={(e) => {
        e.currentTarget.style.borderColor = 'rgba(0, 98, 255, 0.3)';
        e.currentTarget.style.color = '#0062FF';
        e.currentTarget.style.background = 'rgba(0, 98, 255, 0.08)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.borderColor = 'hsl(var(--border))';
        e.currentTarget.style.color = 'hsl(var(--muted-foreground))';
        e.currentTarget.style.background = 'transparent';
      }}
    >
      ↓ Download Onboarding Kit as Markdown
    </button>
  );
}

// Made with Bob
